<script>
  import Nav from '../components/nav.svelte';
</script>
<!-- TODO: change loggedout-value in production -->
<Nav title="Welcome to your wing"/>
<!-- login page -->
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
<p>This is the login page for the wing.</p>
